name: Checkmarx One Scan
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '00 7 * * *' # Every day at 07:00

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  cx-scan:
    name: Checkmarx One Scan
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@b21af721f0f841c9c10f8f87767f4d8df2d13db0 # 2.3.40
        with:
          base_uri: ${{ secrets.AST_RND_SCANS_BASE_URI }}
          cx_tenant: ${{ secrets.AST_RND_SCANS_TENANT }}
          cx_client_id: ${{ secrets.AST_RND_SCANS_CLIENT_ID }}
          cx_client_secret: ${{ secrets.AST_RND_SCANS_CLIENT_SECRET }}
          additional_params: --tags phoenix --threshold "sca-critical=1;sca-high=1;sca-medium=1;sca-low=1;sast-critical=1;sast-high=1;sast-medium=1;sast-low=1;iac-security-critical=1;iac-security-high=1;iac-security-medium=1;iac-security-low=1"
