name: Delete dev releases

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to delete'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to delete'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  delete:
    name: Delete Releases and Tags
    environment: release
    permissions:
      id-token: write  # for OIDC auth
      contents: write  # for deleting releases
      packages: write  # for package management
    runs-on: cx-public-ubuntu-x64
    steps:

      - name: Delete releases and tags
        continue-on-error: true
        uses: dev-drprasad/delete-older-releases@dfbe6be2a006e9475dfcbe5b8d201f1824c2a9fe #v0.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 0
          delete_tag_pattern: "-${{inputs.tag}}"
          delete_tags: true