name: Nightly Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  set_tag:
    name: Generate Release Tag
    runs-on: cx-public-ubuntu-x64
    outputs:
      tag_name: ${{ steps.tagname.outputs.tag_name }}
    steps:
      - name: Create tagname
        run: echo "tag_name=2.0.$(date +%s)" >> "$GITHUB_OUTPUT"
        id: tagname
      - name: Print tagname
        env:
          TAG_NAME: ${{ steps.tagname.outputs.tag_name }}
        run: echo "created tag ${TAG_NAME}"
  nightly: # zizmor: ignore[unpinned-uses]
    name: Nightly Release
    needs: set_tag
    uses: Checkmarx/ast-teamcity-plugin/.github/workflows/release.yml@main # zizmor: ignore[unpinned-uses]
    with:
      tag: ${{ needs.set_tag.outputs.tag_name }}
      rchannels: "nightly"
    secrets: inherit # zizmor: ignore[secrets-inherit]